name: CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uv sync --frozen
      - name: Run tests
        run: uv run pytest -v
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uv sync --frozen
      - name: Build package
        run: uv build
      - use: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/*
